services:
  - type: web
    name: esp32-backend
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install --production
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_TRAFFIC_EVENTS_TABLE
        sync: false
      - key: MAX_MESSAGES
        value: "500"
      - key: DETECTION_THRESHOLD_CM
        value: "30"
      - key: PRESENCE_TIMEOUT_MS
        value: "10000"
      - key: MIN_GREEN_MS
        value: "8000"
      - key: MAX_GREEN_MS
        value: "20000"
      - key: YELLOW_MS
        value: "3000"
      - key: MAX_RED_MS
        value: "60000"
      - key: HOLD_AFTER_CLEAR_MS
        value: "2000"
      - key: VEHICLE_GAP_HOLD_MS
        value: "4000"
      - key: TICK_INTERVAL_MS
        value: "250"
